version: '3.8'
services:
#  todo-service:
#    build: ./path/to/todo/service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongodb
#      - kafka
#
#  user-service:
#    build: ./path/to/user/service
#    ports:
#      - "8081:8080"
#    depends_on:
#      - mongodb
#      - kafka

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: dasspassword

#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: wurstmeister/kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: kafka
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    depends_on:
#      - zookeeper
#
#  angular-frontend:
#    build: ./path/to/angular/frontend
#    ports:
#      - "80:80"
#    depends_on:
#      - todo-service
#      - user-service
